services:
  app:
    build: .
    image: india_pincode_service
    command: uvicorn main:app --host 0.0.0.0 --port 3000
    working_dir: /app/app/
    ports:
      - 3000:3000
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@database/postgres
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "database:192.168.1.252"