services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
  migration:
    build: migrations/
    working_dir: /app/
    environment:
      DATABASE_URI: postgresql://postgres:postgres@postgres/postgres
      CSV_EXPORT_URI: https://drive.google.com/u/0/uc?id=1M58ZSEBqmLnH0rRCEN5uZfj0FemN6pw3&export=download
    volumes:
      - /bind-mount/PostgreSQL/:/var/lib/postgresql/data
    command: bash -c "python migrate_data.py && alembic upgrade head"
    depends_on:
      - postgres
  app:
    build: app/
    environment:
      DATABASE_URI: postgresql://postgres:postgres@postgres/postgres
    command: uvicorn main:app --host 0.0.0.0 --port 3000
    working_dir: /app/
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - migration

